global:
  scrape_interval:     15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 60s
    static_configs:
      - targets: ["localhost:9090"]

remote_write:
  - url: "<Your Prometheus remote_write endpoint>"
    basic_auth:
      username: "<Your Grafana Username>"
      password: "<Your Grafana API key>"